### ISSUE TITLE
Should the extension be defined in node.extensions.KHR_lights_punctual.extensions?

### ISSUE THREAD

**Issue by takahirox** [takahirox/KHR_lights_shadows#1]
Currently the extension is written against [`KHR_lights_punctual` extension](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_lights_punctual) but the extension is defined in `node.extensions`. Should it be defined in `node.extensions.KHR_lights_punctual.extensions` like the following?

```
nodes : [{
  extensions : {
    KHR_lights_punctual : {
      extensions: {
        KHR_lights_shadows : {
          receive: true
        }
      }
    }
  }
}]
```

**Comment by hybridherbst** [comment]
Came here to ask that - I think it needs to be defined for both, on a node level and on a light level. It's very common to have objects cast and receive shadows only for lights where that is explicitly turned on (e.g. only the first directional light casts shadows).

**Comment by takahirox** [comment]
Hi @hybridherbst thanks for the feedback. I opened another issue #2 because it sounds like a different topic from this thread.

**Comment by takahirox** [comment]
Closing in favor of #6
