### ISSUE TITLE
KHR_lights_shadows as an extension of node or mesh

### ISSUE THREAD

**Issue by querielo** [takahirox/KHR_lights_shadows#19]
The extension was moved [from **node** to **mesh**](https://github.com/takahirox/KHR_lights_shadows/commit/21aa520220ab73d7d988d355f08d904b7130c7f2) and [from mesh to mesh.primitive](https://github.com/takahirox/KHR_lights_shadows/commit/191d25946271ce06db604bb66e480b72caa2c9b8). Is it a semantically correct place?

It looks like **primitives** correspond to the data that is used by draw calls and **mesh**. So, it is a low-level abstraction that is not connected to lightning. As I can see it can cause a few problems:

- Different engines don't store information about shadows in geometry. So, it can increase  the complexity of extension integration. For example:
  - [the **Renderer** component in Unity](https://docs.unity3d.com/ScriptReference/Renderer.html) that stores information about shadow casting/receiving is not connected with geometry primitives, 
  - [mesh](https://threejs.org/docs/index.html?q=mesh#api/en/objects/Mesh) in Three.js can be considered as **node** in glTF. Example: `mesh.castShadow = false; mesh.receiveShadow = true;`,
  - [RenderComponent in Playcanvas](https://developer.playcanvas.com/api/pc.RenderComponent.html) is similar to Unity,
  - in Babylon.js shadow casters (meshes that correspond to **nodes** in glTF) are passed into a render list of shadow generator.

- If different models share the same geometry with different cast/receive parameters we have to create a few **meshes** in terms of glTF or a graphical primitives in terms of GPU. If other glTF extension uses geometry it is not clear which one has to be taken (for example, surface of particle emitter of collision geometry).

I think _KHR_lights_shadows_ can be an extension of **node**. **mesh.primitive** is too low-level geometry abstraction. **mesh** can be considered as a named bunch of **primitives**, so it is also a geometry abstraction. **node** is the next in order. And since nobody stores **castShadow/receiveShadow** in materials (I can be wrong) can we consider **node** as a better place for the extension?

**Comment by takahirox** [comment]
* #12
* https://github.com/KhronosGroup/glTF/pull/2220

**Comment by querielo** [comment]
Oh. I didn't notice that **primitive** has the **material** field. Then everything is right. I close the issue.
