### ISSUE TITLE
Add the capability of defining what lights cast shadows

### ISSUE THREAD

**Issue by takahirox** [takahirox/KHR_lights_shadows#2]
Comment from @hybridherbst https://github.com/takahirox/KHR_lights_shadows/issues/1#issuecomment-1120699405

> I think it needs to be defined for both, on a node level and on a light level. It's very common to have objects cast and receive shadows only for lights where that is explicitly turned on (e.g. only the first directional light casts shadows).

**Comment by takahirox** [comment]
Honestly I'm on the fence about the defenition on a light level.

> It's very common to have objects cast and receive shadows only for lights where that is explicitly turned on

I agree with that it's a common. Casting and receiving shadows only for active (turned on) lights should be natural. But if I'm right [`KHR_lights_punctual`](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_lights_punctual) doesn't have the capability of defining active lights. Probably it is an applications/engines responsibility.

Defining what lights are active is beyond the scope of this extension. If we want to define what lights are active in glTF, probably it would be better to make another extension.

So, currently I'm inclined with not having the definition on a light level (in this extension).

**Comment by hybridherbst** [comment]
I'm not saying we should define what lights are active. An extension dealing with shadows for objects should be able to specify _which lights cast shadows_ though, not which lights are active. 

Otherwise, are you saying you would leave it up to the implementation to decide which lights actually cast shadows? (Then the whole idea of specifying cast/receive on a per-node level doesn't make sense anymore in my opinion, as it is then still unclear what shadows should actually be drawn)

A typical case for a singular product is a three-point light setup with a directional light and two spot lights - almost always one wants only the directional light to cast shadows, not the "filler" spotlights.

**Comment by takahirox** [comment]
> A typical case for a singular product is a three-point light setup with a directional light and two spot lights - almost always one wants only the directional light to cast shadows, not the "filler" spotlights.

Let me confirm my understanding. In this example, there are one directional light and two directional lights in a scene. **All they are turned on.** But only the directional light casts shadows while the two spot lights don't. Is this correct?

If so, ok it may make sense to me. Just defining whether a light has the ability of casting shadows. Not complex as an extension.

**Comment by takahirox** [comment]
A new question is coming up if we add the capacility of defining what lights cast shadows. Which should it be in, node level extension (`nodes.extensions`) or light level extension (`extensions.KHR_lights_punctual.lights.extensions`)?

Currently `cast/receive` for objects are defined in node level, not mesh level. It allows that even if two or more nodes refer to the same mesh the nodes (objects) can have different `cast/receive` values.

I think lights should follow the same rule for the consistency and flexibility, like

```
"nodes" : [{
  "extensions" : {
    "KHR_lights_punctual" : {
      "light" : 0
    },
    "KHR_lights_shadows": {
      // I didn't come up with a good property name yet
      "castForLight": true
    }
  }
}]
```

**Comment by takahirox** [comment]
Added `castForLight`, thanks.
