### ISSUE TITLE
Rename castForLight

### ISSUE THREAD

**Issue by takahirox** [takahirox/KHR_lights_shadows#4]
The property name `castForLight` sounds a bit ugly. It should be renamed to a properer one.

**Comment by hybridherbst** [comment]
Why not also 'cast'?
(that's what Unity does at least)

**Comment by takahirox** [comment]
Because a node can have the both `mesh` and `light`. There may be a case that they need different `cast` values.

**Comment by takahirox** [comment]
Another option might be `cast` for `mesh` is defined in `node.extensions.KHR_lights_shadows` while `cast` for `light` is defined in `node.extensions.KHR_lights_punctual.extenions.KHR_lights_shadows`

```
"nodes": [{
    "mesh": 0,
    "extensions": {
        "KHR_lights_shadows": {
            "cast": true
        }
    }
}, {
    "extensions" : {
        "KHR_lights_punctual" : {
            "light" : 0,
            "extensions" : {
                "KHR_lights_shadows": {
                    "cast": true
                }
            }
        }
    }
}, {
    "mesh": 1,
    "extensions": {
        "KHR_lights_shadows": {
            "cast": true
        },
        "KHR_lights_punctual" : {
            "light" : 1,
            "extensions" : {
                "KHR_lights_shadows": {
                    "cast": true
                }
            }
        }
    }
}]
```

Related: #1

**Comment by hybridherbst** [comment]
Ah, yes, I thought that would make more sense to have it on the light definition in the extension.

Out of curiosity, are you aware of an example where the same light is used on multiple nodes? I haven't seen that, but can imagine that happening (e.g. having 100 of the same light fixtures on a ceiling). The above would still work then and I think be pretty clear to define.

**Comment by takahirox** [comment]
> Out of curiosity, are you aware of an example where the same light is used on multiple nodes? 

No, but I can imagine, too.

**Comment by takahirox** [comment]
Closing in favor of #6
